# Site Settings
title: "Lindsay Millard – Excellence in Hydrologic Analysis"
description: "Flood modelling and hydraulic analysis services. Specialising in TUFLOW, HEC-RAS, and flood risk assessment for infrastructure projects across Australia."
locale: "en-AU"
url: "https://lmillard79.github.io"
baseurl: ""
repository: "lmillard79/lmillard79.github.io"
remote_theme: pages-themes/cayman@v0.2.0
email: "lindsay.millard@example.com"  # Update with your email

# GitHub Pages
show_downloads: false
github:
  is_project_page: false
  is_user_page: true
  owner: lmillard79
  repo: lmillard79.github.io
  show_downloads: false

# Navigation
nav:
  - name: "Home"
    url: "/"
  - name: "About"
    url: "/about/"
  - name: "Projects"
    url: "/projects/"
  - name: "Blog"
    url: "/blog/"
  - name: "Resources"
    url: "/resources/"

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      show_sidebar: true

# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - Rakefile
  - archive/
  - docs/
  - vendor/

# SEO & Social
seo:
  name: "Lindsay Millard"
  type: Person
  links:
    - "https://github.com/lmillard79"
    - "https://www.linkedin.com/in/lindsaymillard"

# Social Media
social:
  github: lmillard79
  linkedin: lindsaymillard
  twitter: lmillard79  # Update or remove if not used

# Analytics
google_analytics: "G-G7EJXT9KGR"  # Add your Google Analytics ID

# Site verification
google_site_verification: ""
bing_site_verification: ""
yandex_site_verification: ""

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

# Sitemap
sitemap:
  priority: 0.7
  lastmod: 2025-09-01
  changefreq: 'monthly'
  exclude: ['/archive/']
naver_site_verification: ""

# Analytics
analytics:
  provider: "google"
  google:
    tracking_id: "G-G7EJXT9KGR"

# Author Info
author:
  name: "Lindsay Millard"
  avatar: "/images/PenPic_WRM.png"
  bio: "Chartered Water Resources Engineer & Data Scientist specialising in hydrological modeling and environmental data analysis"
  location: "Brisbane, Australia"
  email: "lindsay.milard@outlook.com.au"
  github: "lmillard79"
  linkedin: "lindsaymillard"

# Social Profiles
social:
  type: "Person"
  name: "Lindsay Millard"
  links:
    - "https://github.com/lmillard79"
    - "https://www.linkedin.com/in/lindsaymillard"

# Collections
collections:
  pages:
    output: true
    permalink: /:name/

# Pagination & Permalinks
paginate: 5
paginate_path: /page:num/

# Markdown & Syntax
markdown: kramdown
highlighter: rouge
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo

# Custom CSS
include:
  - /assets/css/custom.css

include:
  - /assets/css/style.scss

# Sass
sass:
  sass_dir: _sass
  style: compressed

# Layout Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Search
search: true
search_full_content: true

# Breadcrumbs
breadcrumbs: true

# Performance & Clean Build
exclude:
  - node_modules
  - vendor
  - .sass-cache
  - .jekyll-assets-cache
  - Gemfile
  - Gemfile.lock
  - README
  - /docs
  - /test

# Debug settings
verbose: true
liquid:
  error_mode: strict

keep_files:
  - .git
  - .svn

encoding: "utf-8"
incremental: false
