# Site Identity
title: "Lindsay Millard – Flood Modeling & Hydrological Analysis Expert"
name: "Lindsay Millard"
description: "Expert flood modeling and hydraulic analysis services. Specializing in TUFLOW, HEC-RAS, and flood risk assessment for infrastructure projects across Australia."
locale: "en-US"
url: "https://lmillard79.github.io"
baseurl: ""
repository: "lmillard79/lmillard79.github.io"
minimal_mistakes_skin: "default"

# SEO
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jemoji
  - jekyll-seo-tag
  - jekyll-compress-html  

google_site_verification: "your-google-verification-code-here"
bing_site_verification: "your-bing-verification-code-here"
yandex_site_verification: ""
naver_site_verification: ""

# Analytics
analytics:
  provider: "google"
  google:
    tracking_id: "G-G7EJXT9KGR"

# Author Info
author:
  name: "Lindsay Millard"
  avatar: "/images/PenPic_WRM.png"
  bio: "Chartered Water Resources Engineer & Data Scientist specialising in hydrological modeling and environmental data analysis"
  location: "Brisbane, Australia"
  email: "lindsay.milard79@gmail.com"
  github: "lmillard79"
  linkedin: "lindsaymillard"

# Social Profiles
social:
  type: "Person"
  name: "Lindsay Millard"
  links:
    - "https://github.com/lmillard79"
    - "https://www.linkedin.com/in/lindsaymillard"

# Pagination & Permalinks
paginate: 5
paginate_path: /page:num/
permalink: /:categories/:title/

# Markdown & Syntax
markdown: kramdown
highlighter: rouge
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo

# Sass
sass:
  sass_dir: _sass
  style: compressed

# Layout Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development

# Search
search: true
search_full_content: true

# Breadcrumbs
breadcrumbs: true

# Performance & Clean Build
exclude:
  - node_modules
  - vendor
  - .sass-cache
  - .jekyll-assets-cache
  - Gemfile
  - Gemfile.lock
  - README
  - /docs
  - /test

keep_files:
  - .git
  - .svn

encoding: "utf-8"
incremental: false
