# Local development configuration
# Overrides settings in _config.yml for local development

url: "http://localhost:4000"
environment: development

# Enable verbose output for debugging
verbose: true

# Enable incremental builds for faster development
incremental: true

# Show drafts
draft: true

# Disable caching for development
sass:
  style: expanded
  trace_selectors: true
  debug_info: true
  line_numbers: true
  sourcemap: true

# Enable livereload for development
livereload: true
